### Валидный запрос на создание offer
POST http://localhost:3000/api/offers
Content-Type: application/json
Cache-Control: no-cache

{
  "type": "Куплю",
  "title": "Заголовок",
  "description": "Описание",
  "sum": 40000,
  "picture": "Картинка",
  "categoryList": ["Категория 1", "Категория 2", "Категория 3"]
}


### Невалидный запрос на создание offer
POST http://localhost:3000/api/offers
Content-Type: application/json
Cache-Control: no-cache

{
  "type": "Куплю",
  "title": "Заголовок",
  "description": "Описание",
  "picture": "Картинка"
}

### Получение offer по ID
GET http://localhost:3000/api/offers/pjKE6yKs7gAdfRu8jrJIv
Content-Type: application/json

### редактирование предложения
PUT http://localhost:3000/api/offers/ttk0HMqbQs1ruKd8-oqhd
Content-Type: application/json

{
  "type": "buy",
  "title": "title",
  "description": "description",
  "sum": 5000,
  "picture": "picture",
  "categoryList": [
    "Категория 4"
  ]
}

### для проверки на ошибку при редактировании предложения
PUT http://localhost:3000/api/offers/ttk0HMqbQs1ruKd8-oqhd
Content-Type: application/json

{
  "_type": "buy",
  "name": "title",
  "description": "description",
  "sum": 10000,
  "picture": "picture",
  "categoryList": [
    "Категория 4"
  ]
}

### Удаление предложения
DELETE http://localhost:3000/api/offers/asZrd-K3uR2I41cn9KQQH

###
