### Получить список комментариев для предложения
GET http://localhost:3000/api/offers/U7fBtKlBluanMvm6gn4Mg/comments
Content-Type: application/json

### Добавить новый комментарий
POST http://localhost:3000/api/offers/U7fBtKlBluanMvm6gn4Mg/comments
Content-Type: application/json

{
  "text": "Новый комментарий!!!"
}

### Отправка несуществующего поля
POST http://localhost:3000/api/offers/U7fBtKlBluanMvm6gn4Mg/comments
Content-Type: application/json

{
  "texxt": "Новый комментарий!!!"
}

### отправка с отсутствующим комментарием
POST http://localhost:3000/api/offers/U7fBtKlBluanMvm6gn4Mg/comments
Content-Type: application/json

{}

### Удаление комментария для предложения
DELETE http://localhost:3000/api/offers/U7fBtKlBluanMvm6gn4Mg/comments/S-mzlZnIr25by5najZNdk

###
